### ISSUE TITLE
Request JMS operators to support amqps protocol

### ISSUE THREAD

**Issue by conglisc** [IBMStreams/streamsx.jms#3]
Request JM operators to support AMQP and AMQPS procotol. This would require following changes
1. Minor code change.
2. Doc update for setting up proper amqp libs and configuration files

**Comment by schubon** [comment]
Refering to [Understanding the Differences between AMQP and JMS](http://www.wmrichards.com/amqp.pdf), I come to the following conclusion:
AMQP and JMS are different implementations of the message queue/topic idea, but that doesn't mean there is something like JMS via AMQP. There are some brokers that are capable of translating between JMS and AMQP clients, but that is something different than having JMS operators behaving like AMQP operators. Furthermore, RabbitMQ is an implementation of AMQP, so we ALREADY HAVE operators for AMQP in our [RabbitMQ toolkit](https://github.com/IBMStreams/streamsx.rabbitmq).

This issue is baseless and I am going to close it now.
